name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -rf .next
          rm -rf out
          npm ci

      - name: Build
        run: |
          # Skip linting during build
          NEXT_LINT_DURING_BUILD=false npm run build
          touch out/.nojekyll  # Prevent GitHub Pages from processing with Jekyll
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
